@php
    // Default / Mock data so the page works out of the box even without controller variables
    $lecturerName = $lecturerName ?? 'Heri Setyawan, M.Kom.';
    $nidn = $nidn ?? '123456789';
    $roles = $roles ?? [
        ['name' => 'Kaprodi', 'bg' => 'bg-amikom-purple'],
        ['name' => 'Dosen Wali', 'bg' => 'bg-amikom-gold'],
        ['name' => 'Dosen Pembimbing', 'bg' => 'bg-amikom-green'],
    ];
@endphp

@extends('layouts.dosen')

@section('title', 'Layanan Dokumen - Detail Permintaan Persetujuan')

@section('content')
<div class="space-y-8">
    <!-- Breadcrumbs & Header -->
    <div class="mb-4">
        <nav class="flex items-center gap-2 text-gray-400 mb-3">
            <a class="font-body-sm text-body-sm hover:text-primary transition-colors" href="{{ url('/lecturer/approval') }}">Persetujuan Dokumen</a>
            <span class="material-symbols-outlined text-[16px]">chevron_right</span>
            <span class="font-label-sm text-label-sm text-gray-900 uppercase tracking-wider">Detail Permintaan</span>
        </nav>
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
                <h2 class="text-2xl font-bold text-gray-900 mb-2">Detail Pengajuan Surat Keterangan Aktif</h2>
                <p class="font-body-md text-body-md text-gray-500 flex items-center gap-2">
                    <span class="material-symbols-outlined text-[18px]">calendar_today</span>
                    Diajukan pada 12 Oktober 2023
                </p>
            </div>
            <div class="inline-flex items-center gap-2 px-4 py-2 bg-[#FEF3C7] border border-[#FDE68A] rounded-full self-start">
                <span class="w-2 h-2 rounded-full bg-secondary"></span>
                <span class="font-label-lg text-label-lg text-[#92400E]">Menunggu Persetujuan</span>
            </div>
        </div>
    </div>

    <!-- Bento Grid Layout -->
    <div class="grid grid-cols-1 xl:grid-cols-12 gap-6">
        <!-- Left Column: Document Viewer -->
        <div class="xl:col-span-8 flex flex-col gap-6">
            <div class="bg-white border border-gray-200 rounded-xl flex flex-col shadow-sm">
                <div class="px-6 py-4 border-b border-gray-200 flex items-center justify-between bg-white">
                    <div class="flex items-center gap-3">
                        <span class="material-symbols-outlined text-primary">description</span>
                        <div>
                            <h3 class="font-label-lg text-label-lg text-gray-900">Surat_Keterangan_Aktif_Draft.pdf</h3>
                            <p class="text-[12px] text-gray-400 font-body-sm">245 KB • Generated by System</p>
                        </div>
                    </div>
                    <div class="flex gap-2">
                        <button class="p-2 text-gray-500 hover:bg-gray-100 rounded-lg transition-colors">
                            <span class="material-symbols-outlined">zoom_in</span>
                        </button>
                        <button class="p-2 text-gray-500 hover:bg-gray-100 rounded-lg transition-colors">
                            <span class="material-symbols-outlined">zoom_out</span>
                        </button>
                        <div class="w-px h-6 bg-gray-200 my-auto mx-1"></div>
                        <button class="p-2 text-primary hover:bg-primary/10 rounded-lg transition-colors flex items-center gap-1">
                            <span class="material-symbols-outlined">download</span>
                            <span class="font-label-sm text-label-sm hidden sm:inline font-semibold">Unduh File</span>
                        </button>
                    </div>
                </div>
                <div class="flex-1 bg-gray-50 p-8 flex justify-center overflow-x-auto">
                    <div class="w-full max-w-[600px] bg-white shadow-[0_4px_12px_rgba(0,0,0,0.08)] border border-gray-200 min-h-[800px] p-12 shrink-0">
                        <div class="border-b-2 border-[#410063] pb-6 mb-8 text-center">
                            <h4 class="font-title-lg text-title-lg font-bold text-primary uppercase tracking-widest">Universitas Amikom</h4>
                            <p class="font-body-sm text-body-sm text-gray-400 mt-1">Fakultas Ilmu Komputer</p>
                        </div>
                        <h5 class="font-label-lg text-label-lg text-center mb-8 underline">SURAT KETERANGAN AKTIF KULIAH</h5>
                        <div class="space-y-4 font-body-sm text-body-sm text-gray-900">
                            <p class="">Yang bertanda tangan di bawah ini, Dekan Fakultas Ilmu Komputer menerangkan bahwa:</p>
                            <div class="grid grid-cols-[150px_1fr] gap-2 pl-4">
                                <div class="font-semibold">Nama</div><div class="">: Budi Santoso</div>
                                <div class="font-semibold">NIM</div><div class="">: 19.11.1234</div>
                                <div class="font-semibold">Program Studi</div><div class="">: D3 Teknik Informatika</div>
                                <div class="font-semibold">Semester</div><div class="">: V (Lima)</div>
                            </div>
                            <p class="pt-4">Adalah benar mahasiswa yang bersangkutan aktif mengikuti perkuliahan pada semester Ganjil Tahun Akademik 2023/2024.</p>
                            <p class="">Surat keterangan ini dibuat untuk keperluan: <strong>Pengajuan Beasiswa Prestasi</strong>.</p>
                            <div class="mt-16 text-right">
                                <p class="">Yogyakarta, 12 Oktober 2023</p>
                                <p class="">Mengetahui,</p>
                                <div class="h-20"></div>
                                <p class="font-semibold">Dr. Heri Santoso</p>
                                <p class="text-xs">NIDN: 0611028401</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Column: Student Info, Roles & Details -->
        <div class="xl:col-span-4 flex flex-col gap-6">
            <!-- Student Profile Card -->
            <div class="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                <h3 class="font-title-lg text-title-lg text-gray-900 mb-6 flex items-center gap-2 pb-3 border-b border-gray-200">
                    <span class="material-symbols-outlined text-primary">person_search</span>
                    Informasi Mahasiswa
                </h3>
                <div class="flex items-center gap-4 mb-8">
                    <div class="relative">
                        <img alt="Student Photo" class="w-20 h-20 rounded-xl object-cover border-2 border-primary/10 shadow-sm" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAI8U6QdliiTjyZkmQbBg28RYGNyEZiVLatEqMLpzH_ob8gvGl3P0O3s-Qt3Fc_D79jcaahFcbv3qSGezuoYVvawMrNM46hPYZSlOtyaAlPOojd2ZNhDPc1JYxE7y4tEponJE2zSBgJXYCeIo86cW_9J3AKqWvThHpMPKk9_JoTHl67QUOIb6pY3uPxrBpOxsik07pJOMRi5tfE-Y5BWv_wSM8ZGJ0l6pO-W_bb1XcmX1-qIBDqQRuXnyhiZkKKhr43d09ocXNKJ80">
                        <div class="absolute -bottom-1 -right-1 w-6 h-6 bg-secondary rounded-full border-2 border-white flex items-center justify-center">
                            <span class="material-symbols-outlined text-white text-[14px]">verified</span>
                        </div>
                    </div>
                    <div>
                        <p class="text-xl font-bold text-gray-900 leading-tight">Budi Santoso</p>
                        <p class="font-body-md text-primary font-semibold mt-1">19.11.1234</p>
                    </div>
                </div>
                <div class="space-y-3">
                    <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-100">
                        <div class="flex items-center gap-3">
                            <div class="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                                <span class="material-symbols-outlined text-primary text-[20px]">school</span>
                            </div>
                            <span class="font-label-sm text-label-sm text-gray-500 uppercase tracking-wider font-semibold">Program Studi</span>
                        </div>
                        <span class="font-body-sm text-body-sm text-primary bg-primary/10 px-3 py-1 rounded-full font-bold">D3 Teknik Informatika</span>
                    </div>
                    <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-100">
                        <div class="flex items-center gap-3">
                            <div class="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                                <span class="material-symbols-outlined text-primary text-[20px]">trending_up</span>
                            </div>
                            <span class="font-label-sm text-label-sm text-gray-500 uppercase tracking-wider font-semibold">Status</span>
                        </div>
                        <span class="font-body-sm text-body-sm text-[#584409] bg-[#ffe16d] px-3 py-1 rounded-full font-bold">Aktif (Sem. 5)</span>
                    </div>
                    <div class="grid grid-cols-2 gap-3">
                        <div class="p-3 bg-blue-50 rounded-xl border border-blue-100">
                            <p class="font-label-sm text-label-sm text-blue-800 uppercase tracking-wider mb-1 font-semibold">Total SKS</p>
                            <div class="inline-block bg-blue-100 px-3 py-1 rounded-lg">
                                <p class="font-title-lg text-title-lg text-blue-800 font-bold">110</p>
                            </div>
                        </div>
                        <div class="p-3 bg-green-50 rounded-xl border border-green-100">
                            <p class="font-label-sm text-label-sm text-green-800 uppercase tracking-wider mb-1 font-semibold">IPK</p>
                            <div class="inline-block bg-green-100 px-3 py-1 rounded-lg">
                                <p class="font-title-lg text-title-lg text-green-800 font-bold">3.85</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Lecturer Roles Detail Card -->
            <div class="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                <h3 class="font-title-lg text-title-lg text-gray-900 mb-6 flex items-center gap-2 pb-3 border-b border-gray-200">
                    <span class="material-symbols-outlined text-primary">badge</span>Peran Dosen
                </h3>
                <div class="">
                    <div class="flex items-center justify-between border-b border-gray-100 last:border-0 py-3">
                        <div class="flex flex-col gap-1.5">
                            <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-amikom-purple self-start">Kaprodi</span>
                            <span class="text-body-md font-semibold text-gray-900">Heri Setyawan, M.Kom.</span>
                        </div>
                    </div>
                    <div class="flex items-center justify-between border-b border-gray-100 last:border-0 py-3">
                        <div class="flex flex-col gap-1.5">
                            <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-amikom-gold self-start">Dosen Wali</span>
                            <span class="text-body-md font-semibold text-gray-900">Heri Setyawan, M.Kom.</span>
                        </div>
                    </div>
                    <div class="flex items-center justify-between border-b border-gray-100 last:border-0 py-3">
                        <div class="flex flex-col gap-1.5">
                            <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-amikom-green self-start">Dosen Pembimbing</span>
                            <span class="text-body-md font-semibold text-gray-900">Heri Setyawan, M.Kom.</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Detail Pengajuan Card -->
            <div class="bg-white border border-gray-200 rounded-xl p-6 shadow-sm space-y-6">
                <div class="pb-4 border-b border-gray-100">
                    <h3 class="font-title-lg text-title-lg text-gray-900 mb-4 flex items-center gap-2"><span class="material-symbols-outlined text-primary">info</span>Detail Pengajuan</h3>
                    <div class="space-y-1">
                        <p class="text-label-sm text-gray-500 uppercase tracking-wider font-semibold">Tujuan Dokumen</p>
                        <p class="text-body-md font-medium text-gray-900">Pengajuan Beasiswa Prestasi Kemendikbud 2023</p>
                    </div>
                </div>
                <div>
                    <h3 class="font-title-lg text-title-lg text-gray-900 mb-6 flex items-center gap-2"><span class="material-symbols-outlined text-primary">history</span>Riwayat Status</h3>
                    <div class="space-y-0">
                        <div class="relative pl-8 pb-8 border-l-2 border-amikom-purple">
                            <div class="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-amikom-purple border-4 border-white shadow-sm"></div>
                            <div class="flex flex-col">
                                <span class="text-label-lg text-gray-900 font-bold">Pengajuan Terkirim</span>
                                <span class="text-body-sm text-gray-500">15 Nov 2023, 09:45</span>
                                <span class="mt-2 inline-flex self-start px-2 py-0.5 bg-green-50 text-green-800 text-[10px] font-bold uppercase rounded border border-green-100">Selesai</span>
                            </div>
                        </div>
                        <div class="relative pl-8 pb-8 border-l-2 border-gray-200">
                            <div class="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-amikom-gold border-4 border-white shadow-sm"></div>
                            <div class="flex flex-col">
                                <span class="text-label-lg text-gray-900 font-bold">Persetujuan Dosen Wali</span>
                                <span class="text-body-sm text-gray-500">Sedang diverifikasi...</span>
                                <span class="mt-2 inline-flex self-start px-2 py-0.5 bg-blue-50 text-blue-700 text-[10px] font-bold uppercase rounded border border-blue-100">Proses</span>
                            </div>
                        </div>
                        <div class="relative pl-8">
                            <div class="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-gray-200 border-4 border-white shadow-sm"></div>
                            <div class="flex flex-col">
                                <span class="text-label-lg text-gray-400 font-bold">Verifikasi Program Studi</span>
                                <span class="text-body-sm text-gray-400">Akan datang</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Actions & Notes Card -->
            <div class="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                <h3 class="font-title-lg text-title-lg text-gray-900 mb-4 flex items-center gap-2 pb-3 border-b border-gray-200">
                    <span class="material-symbols-outlined text-primary">edit_note</span>
                    Tindakan
                </h3>
                <div class="flex gap-3 pt-2">
                    <button class="flex-1 py-3 px-4 border border-error text-error font-bold rounded-xl hover:bg-error/5 transition-colors flex items-center justify-center gap-2" onclick="toggleModal('reject-modal', true)">
                        <span class="material-symbols-outlined">close</span>
                        Tolak
                    </button>
                    <button class="flex-[2] py-3 px-4 bg-primary text-white font-bold rounded-xl hover:bg-primary-container shadow-sm transition-colors flex items-center justify-center gap-2" onclick="toggleModal('approve-modal', true)">
                        <span class="material-symbols-outlined">check_circle</span>
                        Setujui Dokumen
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="h-12"></div>
</div>

<!-- Success Toast -->
<div class="fixed bottom-8 left-1/2 -translate-x-1/2 z-[100] opacity-0 pointer-events-none transform translate-y-4" id="success-toast">
    <div class="bg-gray-900 text-white px-6 py-4 rounded-xl shadow-2xl flex items-center gap-3">
        <span class="material-symbols-outlined text-green-400">check_circle</span>
        <span class="font-bold">Dokumen berhasil disetujui!</span>
    </div>
</div>

<!-- Rejection Reason Modal -->
<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm hidden" id="reject-modal">
    <div class="bg-white rounded-xl shadow-2xl w-full max-w-md p-6 border border-gray-200 font-title-lg">
        <div class="flex items-center gap-2 mb-4 p-3 bg-blue-50 border border-blue-100 rounded-lg">
            <span class="material-symbols-outlined text-blue-600 text-[20px]">info</span>
            <p class="text-xs text-blue-700 font-medium">Peran yang tidak dicentang akan tetap berada pada status saat ini.</p>
        </div>
        <h3 class="text-xl font-bold text-gray-900 mb-2 text-primary">Konfirmasi Penolakan</h3>
        <p class="text-sm text-gray-500 mb-6">Pilih peran Anda dan berikan alasan penolakan:</p>
        
        <div class="space-y-4 mb-8">
            <!-- Kaprodi Role -->
            <div class="role-group border rounded-xl overflow-hidden transition-all border-gray-200" id="group-kaprodi">
                <label class="flex items-center gap-3 p-4 bg-gray-50 cursor-pointer">
                    <input checked class="role-checkbox w-5 h-5 rounded border-gray-300 text-error focus:ring-error" onchange="handleRoleToggle('kaprodi')" type="checkbox">
                    <div class="flex flex-col">
                        <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-primary self-start mb-1">KAPRODI</span>
                    </div>
                </label>
                <div class="reason-fields p-4 bg-white border-t border-gray-100 space-y-3 hidden" id="fields-kaprodi">
                    <div>
                        <label class="block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Alasan Penolakan</label>
                        <select class="w-full bg-gray-50 border border-gray-200 rounded-lg p-2 text-sm focus:ring-1 focus:ring-primary outline-none">
                            <option value="sks">Syarat SKS tidak terpenuhi</option>
                            <option value="visi">Judul tidak sesuai visi keilmuan prodi</option>
                            <option value="slot">Slot Dosen Pembimbing penuh</option>
                            <option value="lainnya">Lainnya</option>
                        </select>
                    </div>
                    <textarea class="w-full bg-gray-50 border border-gray-200 rounded-lg p-2 text-sm resize-none focus:ring-1 focus:ring-primary outline-none" placeholder="Catatan Tambahan..." rows="2"></textarea>
                </div>
            </div>

            <!-- Dosen Wali Role -->
            <div class="role-group border border-gray-200 rounded-xl overflow-hidden transition-all" id="group-wali">
                <label class="flex items-center gap-3 p-4 bg-gray-50 cursor-pointer">
                    <input class="role-checkbox w-5 h-5 rounded border-gray-300 text-error focus:ring-error" onchange="handleRoleToggle('wali')" type="checkbox">
                    <div class="flex flex-col">
                        <span class="text-[10px] font-bold text-[#6e5c00] uppercase tracking-widest px-3 py-1 rounded-full bg-[#fcd400] self-start mb-1">DOSEN WALI</span>
                    </div>
                </label>
                <div class="reason-fields p-4 bg-white border-t border-gray-100 space-y-3 hidden" id="fields-wali">
                    <div>
                        <label class="block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Alasan Penolakan</label>
                        <select class="w-full bg-gray-50 border border-gray-200 rounded-lg p-2 text-sm focus:ring-1 focus:ring-primary outline-none">
                            <option value="admin">Masalah administrasi</option>
                            <option value="etika">Etika bimbingan</option>
                            <option value="lainnya">Lainnya</option>
                        </select>
                    </div>
                    <textarea class="w-full bg-gray-50 border border-gray-200 rounded-lg p-2 text-sm resize-none focus:ring-1 focus:ring-primary outline-none" placeholder="Catatan Tambahan..." rows="2"></textarea>
                </div>
            </div>

            <!-- Dosen Pembimbing Role -->
            <div class="role-group border border-gray-200 rounded-xl overflow-hidden transition-all" id="group-pembimbing">
                <label class="flex items-center gap-3 p-4 bg-gray-50 cursor-pointer">
                    <input class="role-checkbox w-5 h-5 rounded border-gray-300 text-error focus:ring-error" onchange="handleRoleToggle('pembimbing')" type="checkbox">
                    <div class="flex flex-col">
                        <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-amikom-green self-start mb-1">PEMBIMBING</span>
                    </div>
                </label>
                <div class="reason-fields p-4 bg-white border-t border-gray-100 space-y-3 hidden" id="fields-pembimbing">
                    <div>
                        <label class="block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Alasan Penolakan</label>
                        <select class="w-full bg-gray-50 border border-gray-200 rounded-lg p-2 text-sm focus:ring-1 focus:ring-primary outline-none">
                            <option value="materi">Materi tidak sesuai</option>
                            <option value="jadwal">Jadwal penuh</option>
                            <option value="lainnya">Lainnya</option>
                        </select>
                    </div>
                    <textarea class="w-full bg-gray-50 border border-gray-200 rounded-lg p-2 text-sm resize-none focus:ring-1 focus:ring-primary outline-none" placeholder="Catatan Tambahan..." rows="2"></textarea>
                </div>
            </div>
        </div>

        <div class="flex gap-3 justify-end">
            <button class="py-2.5 px-6 text-gray-700 hover:bg-gray-100 rounded-lg font-bold transition-colors border border-gray-300" onclick="toggleModal('reject-modal', false)">Batal</button>
            <button class="py-2.5 px-6 bg-error text-white rounded-lg font-bold hover:bg-error/90 transition-colors shadow-lg disabled:opacity-50 disabled:cursor-not-allowed" id="confirm-reject-btn" onclick="confirmRejection()">Konfirmasi Penolakan</button>
        </div>
    </div>
</div>

<!-- Confirm Approval Modal -->
<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm hidden" id="approve-modal">
    <div class="bg-white rounded-xl shadow-2xl w-full max-w-md p-6 border border-gray-200 font-title-lg">
        <h3 class="text-xl font-bold text-primary mb-2">Konfirmasi Persetujuan</h3>
        <p class="text-sm text-gray-500 mb-6">Pilih peran Anda untuk memberikan persetujuan pada dokumen ini:</p>
        
        <div class="space-y-2 mb-8">
            <label class="flex items-center p-3 bg-gray-50 rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-100 transition-colors justify-start gap-3">
                <input class="approve-role-checkbox w-5 h-5 rounded border-gray-300 text-primary focus:ring-primary" onchange="updateApproveButtonState()" type="checkbox">
                <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-primary">KAPRODI</span>
            </label>
            <label class="flex items-center p-3 bg-gray-50 rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-100 transition-colors justify-start gap-3">
                <input class="approve-role-checkbox w-5 h-5 rounded border-gray-300 text-primary focus:ring-primary" onchange="updateApproveButtonState()" type="checkbox">
                <span class="text-[10px] font-bold text-[#6e5c00] uppercase tracking-widest px-3 py-1 rounded-full bg-[#fcd400]">DOSEN WALI</span>
            </label>
            <label class="flex items-center p-3 bg-gray-50 rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-100 transition-colors justify-start gap-3">
                <input class="approve-role-checkbox w-5 h-5 rounded border-gray-300 text-primary focus:ring-primary" onchange="updateApproveButtonState()" type="checkbox">
                <span class="text-[10px] font-bold text-white uppercase tracking-widest px-3 py-1 rounded-full bg-amikom-green">PEMBIMBING</span>
            </label>
        </div>
        
        <div class="flex gap-3 justify-end">
            <button class="py-2.5 px-6 text-gray-500 hover:bg-gray-100 rounded-lg font-bold transition-colors border border-gray-300" onclick="toggleModal('approve-modal', false)">Batal</button>
            <button class="py-2.5 px-6 bg-primary text-white rounded-lg font-bold hover:bg-primary-container shadow-sm disabled:opacity-50 disabled:cursor-not-allowed transition-all" id="confirm-approve-btn" onclick="confirmApproval()">Setujui</button>
        </div>
    </div>
</div>

<script>
    function toggleModal(id, show) {
        const modal = document.getElementById(id);
        if (show) {
            modal.classList.remove('hidden');
            if (id === 'reject-modal') {
                // Trigger handleRoleToggle on initially selected elements to expand the fields correctly
                const checkboxes = modal.querySelectorAll('.role-checkbox');
                checkboxes.forEach(cb => {
                    const roleId = cb.getAttribute('onchange').match(/'([^']+)'/)[1];
                    handleRoleToggle(roleId);
                });
            }
            updateConfirmButtonState();
            updateApproveButtonState();
        } else {
            modal.classList.add('hidden');
        }
    }

    function handleRoleToggle(roleId) {
        const group = document.getElementById(`group-${roleId}`);
        const fields = document.getElementById(`fields-${roleId}`);
        if (!group || !fields) return;
        const checkbox = group.querySelector('.role-checkbox');

        if (checkbox.checked) {
            group.classList.add('border-error');
            group.classList.remove('border-gray-200');
            fields.classList.remove('hidden');
        } else {
            group.classList.remove('border-error');
            group.classList.add('border-gray-200');
            fields.classList.add('hidden');
        }
        updateConfirmButtonState();
    }

    function updateConfirmButtonState() {
        const checkboxes = document.querySelectorAll('.role-checkbox');
        const confirmBtn = document.getElementById('confirm-reject-btn');
        if (!confirmBtn) return;
        const anyChecked = Array.from(checkboxes).some(cb => cb.checked);
        confirmBtn.disabled = !anyChecked;
    }

    function confirmRejection() {
        toggleModal('reject-modal', false);
        showSuccessToast('Dokumen ditolak');
    }

    function updateApproveButtonState() {
        const checkboxes = document.querySelectorAll('.approve-role-checkbox');
        const confirmBtn = document.getElementById('confirm-approve-btn');
        if (!confirmBtn) return;
        const anyChecked = Array.from(checkboxes).some(cb => cb.checked);
        confirmBtn.disabled = !anyChecked;
    }

    function confirmApproval() {
        toggleModal('approve-modal', false);
        showSuccessToast('Dokumen berhasil disetujui!');
    }

    function showSuccessToast(message) {
        const toast = document.getElementById('success-toast');
        if (!toast) return;
        
        if (message) {
            toast.querySelector('.font-bold').textContent = message;
        }

        toast.classList.remove('opacity-0', 'pointer-events-none', 'translate-y-4');
        toast.classList.add('opacity-100', 'translate-y-0');
        
        setTimeout(() => {
            toast.classList.add('opacity-0', 'pointer-events-none', 'translate-y-4');
            toast.classList.remove('opacity-100', 'translate-y-0');
        }, 3000);
    }

    // Initialize button state
    document.addEventListener('DOMContentLoaded', () => {
        updateConfirmButtonState();
        updateApproveButtonState();
    });
</script>
@endsection
