import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "amikom-purple": "#431E6D",
                "amikom-purple-light": "#F3E8FF",
                "amikom-gold": "#E28800",
                "amikom-green": "#0E7452",
                "surface-tint": "#7e45a0",
                "tertiary-fixed": "#ffdf96",
                "on-error": "#ffffff",
                "on-surface-variant": "#4d4450",
                "surface-variant": "#e3e2e2",
                "surface-container-high": "#e9e8e7",
                "on-primary-fixed": "#30004b",
                "tertiary": "#332500",
                "secondary-container": "#fcd400",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "error": "#ba1a1a",
                "surface-container-highest": "#e3e2e2",
                "background": "#fbf9f9",
                "on-background": "#1b1c1c",
                "surface-bright": "#fbf9f9",
                "inverse-on-surface": "#f2f0f0",
                "surface-container-low": "#f5f3f3",
                "secondary-fixed": "#ffe16d",
                "on-secondary-fixed-variant": "#544600",
                "inverse-surface": "#303031",
                "on-secondary-fixed": "#221b00",
                "primary": "#410063",
                "secondary": "#705d00",
                "tertiary-fixed-dim": "#e1c37d",
                "surface": "#fbf9f9",
                "on-primary": "#ffffff",
                "tertiary-container": "#4d3a00",
                "primary-fixed-dim": "#e5b4ff",
                "pure-white": "#FFFFFF",
                "on-tertiary-container": "#c0a461",
                "error-container": "#ffdad6",
                "outline": "#7e7481",
                "on-secondary": "#ffffff",
                "on-primary-container": "#cc8ff0",
                "on-secondary-container": "#6e5c00",
                "deep-black": "#1A1A1A",
                "surface-container": "#efeded",
                "outline-variant": "#cfc2d1",
                "secondary-fixed-dim": "#e9c400",
                "on-surface": "#1b1c1c",
                "on-tertiary-fixed-variant": "#584409",
                "on-tertiary-fixed": "#251a00",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#642c86",
                "primary-container": "#59207b",
                "surface-dim": "#dbdad9",
                "surface-gray": "#F7F7F7",
                "primary-fixed": "#f5d9ff",
                "inverse-primary": "#e5b4ff"
            },
            spacing: {
                "gutter": "24px",
                "margin-desktop": "48px",
                "base": "8px",
                "container-max": "1280px",
                "margin-mobile": "16px",
                "sidebar-width": "280px",
                "unit": "8px",
                "stack-lg": "32px",
                "stack-sm": "8px",
                "container-padding": "32px",
                "stack-md": "16px"
            },
            fontFamily: {
                sans: ['Public Sans', 'Inter', ...defaultTheme.fontFamily.sans],
                "body-sm": ["Public Sans", "sans-serif"],
                "label-lg": ["Public Sans", "sans-serif"],
                "label-sm": ["Public Sans", "sans-serif"],
                "display-lg": ["Montserrat", "sans-serif"],
                "body-md": ["Public Sans", "sans-serif"],
                "headline-lg-mobile": ["Montserrat", "sans-serif"],
                "body-lg": ["Public Sans", "sans-serif"],
                "headline-lg": ["Montserrat", "sans-serif"],
                "title-lg": ["Montserrat", "sans-serif"],
                "headline-md": ["Montserrat", "sans-serif"],
                "headline-sm": ["Montserrat", "sans-serif"],
                "label-md": ["Public Sans", "sans-serif"]
            },
            fontSize: {
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "500" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
                "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
            }
        },
    },

    plugins: [forms],
};
