<?php

namespace App\Enums;

enum LecturerPosition: string
{
  case ACADEMIC_ADVISOR = 'ACADEMIC_ADVISOR';
  case INTERNSHIP_SUPERVISOR = 'INTERNSHIP_SUPERVISOR';
  case THESIS_SUPERVISOR = 'THESIS_SUPERVISOR';
  case HEAD_OF_STUDY_PROGRAM = 'HEAD_OF_STUDY_PROGRAM';
}
